### ISSUE TITLE
About configuration

### ISSUE THREAD

**Issue by WoodenMaiden** [do4-2022/grobuzin#6]
Right now the credentials are entirely written as a string in [the code](https://github.com/do4-2022/grobuzin/blob/0b4d6f2acdc78175446c2aa269d6a9fcd866c20a/database/init.go).
Moreover, we have two more databases to connect to Grobuzin. 

So do we use environment variables or yaml to configure our databases and the JWT Token?

**Comment by nponsard** [comment]
I'm for environment variables

**Comment by WoodenMaiden** [comment]
I'm down for both

WBU @alexis-langlet

**Comment by alexis-langlet** [comment]
Env variables sounds like a good choice 
It would be good to have a .env.example file in order to keep track of the required env variable too.
